---
format: dashboard
title: ""
theme: 
  - darkly
  - stravawattz.scss
expandable: false
---

```{r script-preparation}
suppressPackageStartupMessages({
  
  library(dplyr)
  library(jsonlite)
  library(httr)
  library(ggplot2)
  library(stringr)
  library(tidyr)
  library(purrr)
  library(lubridate)
  library(leaflet)
  library(DT)
  library(plotly)
  library(openmeteo)
  library(RColorBrewer)
  library(clipr)
  library(scales)
  library(reshape2)
  
})
load("stravawattz.RData")
```

# 2025

## Row {height="20%"}

```{r}
#| content: valuebox
list(
  title = "Running in 2025",
  #icon = "hash",
  color = "success",
  value = 15
)
```

```{r}
#| content: valuebox
list(
  title = "Cycling in 2025",
  #icon = "hash",
  color = "warning",
  value = 15
)
```

```{r}
#| content: valuebox
list(
  title = "Swimming in 2025",
  #icon = "hash",
  color = "info",
  value = 15
)
```

```{r}
#| content: valuebox
list(
  title = "Total distance",
  #icon = "hash",
  color = "dark",
  value = 15
)
```

```{r}
#| content: valuebox
list(
  title = "Total time",
  #icon = "hash",
  color = "dark",
  value = 15
)
```

## Row {height="80%"}

```{r}
#| content: valuebox
list(
  title = "TEST",
  #icon = "hash",
  color = "light",
  value = 15
)
```

# 2024

## Row {height="20%"}

```{r}
#| content: valuebox
list(
  title = "Running in 2024",
  #icon = "hash",
  color = "success",
  value = 15
)
```

```{r}
#| content: valuebox
list(
  title = "Cycling in 2024",
  #icon = "hash",
  color = "warning",
  value = 15
)
```

```{r}
#| content: valuebox
list(
  title = "Swimming in 2024",
  #icon = "hash",
  color = "info",
  value = 15
)
```

```{r}
#| content: valuebox
list(
  title = "Total distance",
  #icon = "hash",
  color = "dark",
  value = 15
)
```

```{r}
#| content: valuebox
list(
  title = "Total time",
  #icon = "hash",
  color = "dark",
  value = 15
)
```

## Row {height="80%"}

```{r}
#| content: valuebox
list(
  title = "TEST",
  #icon = "hash",
  color = "light",
  value = 15
)
```

# 2023

## Row {height="20%"}

```{r}
#| content: valuebox
list(
  title = "Running in 2023",
  #icon = "hash",
  color = "success",
  value = 15
)
```

```{r}
#| content: valuebox
list(
  title = "Cycling in 2023",
  #icon = "hash",
  color = "warning",
  value = 15
)
```

```{r}
#| content: valuebox
list(
  title = "Swimming in 2023",
  #icon = "hash",
  color = "info",
  value = 15
)
```

```{r}
#| content: valuebox
list(
  title = "Total distance",
  #icon = "hash",
  color = "dark",
  value = 15
)
```

```{r}
#| content: valuebox
list(
  title = "Total time",
  #icon = "hash",
  color = "dark",
  value = 15
)
```

## Row {height="80%"}

```{r}
#| content: valuebox
list(
  title = "TEST",
  #icon = "hash",
  color = "light",
  value = 15
)
```
